# Generated by Django 5.0.1 on 2024-01-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=200)),
                ('list_context', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
