# Generated by Django 5.0.1 on 2024-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_list_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
