# Generated by Django 5.0.1 on 2024-01-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_list_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='list_title',
        ),
    ]
